GET http://localhost:8090/business/hello
Accept: application/json

###

GET http://localhost:8000/business/hello
Accept: application/json

###

GET http://localhost:8000/business/admin/train/gen-seat/D2
Accept: application/json